version: '3.8'
services:
  mongo:
    container_name: mongo
    build: ./api/database/mongodb
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    env_file:
      - ./api/.env
    restart: always
    networks:
      - backend
    volumes:
    - ./api/database/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


  api:
    container_name: api
    build: ./api
    ports:
      - ${API_PORT:-8080}:8080
    environment:
      - MONGO_URŞ="mongodb://mongo:27017"
    restart: always
    networks:
      - backend

  frontend:
    container_name: dashboard
    build: ./dashboard
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    restart: on-failure
    networks:
      - backend

networks:
  backend:
    driver: bridge
